feat: docker-compose, poms, project structure
fidgo/java-explore-with-me pull request #1
Opened 2022-11-28 11:36 UTC by fidgo

- Проектирование и подготовка к запуску многомодульного проекта
- Добавление необходимых зависимостей в pom файле
- Подключние БД и проектирование ERM для статистики и основного сервиса. Файлы schema.sql

2022-12-01 16:10 UTC, fidgo commented
* Реализация функционала пользователей.
* Реализация функционала категорий.
* Реализация функционала событий.
* Реализация функционала подборок событий.
* Реализация функционала запросов участия в событиях.
* Доработка клиента статистики.
* Добавление учета статистики.

2022-12-01 20:59 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-01 20:59 UTC, FanaticFiz commented on README.md
> +## Оглавление:
Какой у тебя комплексный и классный подход! 
Очень здорово!

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/CategoryServiceImp.java
> +        return CategoryMapper.toCategoryDto(save);
Есть хорошая практика делать отступ перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/CategoryServiceImp.java
> +        return CategoryMapper.toCategoryDtos(categories);
В целом мне понравилось что ты попытался что-то сделать с этим и придумал метод `toCategoryDtos` !

Но, вот как нужно делать:

```
    @Override
    public List<CategoryDto> getListByPublic(PageRequestFrom pageRequest) {
        return categoryRepository.findAll(pageRequest)
                                 .stream()
                                 .map(CategoryMapper::toCategoryDto)
                                 .collect(Collectors.toList());
    }
```

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/CategoryServiceImp.java
> +        checkArgumentAndIfNullThrowException(catId, "catId");
`checkArgumentAndIfNullThrowException -> throwIfTitleNotValid`

Когда мы говорим check подразумевается проверка с возвращаемым результатом, поэтому это мы из названия выкидываем.
Во второй части названия ты прав! Именно так я и прошу называть такой метод студентов - честно говорим что будет throw если что-то не так.

Ну и я предложил тебе свой вариант исходя из того что я увидел в реализации...

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/CategoryServiceImp.java
> +        Category categoryById = categoryRepository.findById(catId)
Давай на этом кусочке уже ты сам потренируешься... посмотри на предыдущий пример кода...
Вместо 

```
        Category categoryById = categoryRepository.findById(catId)
                                                  .orElseThrow(() -> new NoSuchElemException(
                                                          "Category doesn't exist with id=" + catId));

        return CategoryMapper.toCategoryDto(categoryById);
```

ты должен написать сразу начиная с `return` без переменной `categoryById`

Дальше я на подобные вещи комментировать не буду, думаю ты уже сам найдешь все похожие паттерны и отрефакторишь, а я не буду повторяться... ))

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/compilation/CompilationServiceImp.java
> +                .map((id) -> eventRepository.findById(id)
Плохое решение!
Ты делаешь много запросов по findById вместо того чтобы вытащить их все за один раз!

```
List<Event> events = eventRepository.findAllById(compilationDto.getEvents());
```

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +    public ApiError handleIllegalArgumentException(final IlLegalArgumentException e) {
Все обработчики 
@ResponseStatus(HttpStatus.BAD_REQUEST)
имеют схожий код и должны быть объединены!

Найдешь самостоятельно как это сделать?

Даю тебе задания исключительно потому что вижу что работа у тебя классная и ты точно смогешь!

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/Event.java
> +    private String title;
Возьмём для примера title - в базе он 120 символов... Это надо отразить и в сущности!

Проверь и другие поля и другие сущности...

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/EventServiceImp.java
> +        Map<Long, Long> views = statClient.getViewsForEvents(List.of(publishedEventById), false);
Вот тут сделано правильно!
Получаем всё за один ход, так сказать...

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +        log.info("{}:{}:{}#To create user:{} request on event:{}",
Осмысленная работа с логом - нравится в твоей работе, отлично!

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/user/UserRepository.java
> +    @Query(" select case when count(u) > 0 then true else false end from User u where u.name = :name or u.email = :email")
Оформляй `SQL` запросы. Пиши спец. слова в верхнем регистре: `CREATE`, `FROM`, `AND`

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-main-service/src/main/resources/application.properties
> +server.port=8080
Я знаю, вам этого не давали, но я, всё же, топлю за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу и тебя этому следовать.

2022-12-01 20:59 UTC, FanaticFiz commented on ewm-stats-service/src/main/java/ru/practicum/ewm/Stats.java
> +public class Stats {
Самый крутой класс в приложении... в нём никто не делает ошибок! )))

2022-12-02 19:33 UTC, FanaticFiz approved these changes

2022-12-02 19:33 UTC, FanaticFiz commented on ewm-main-service/src/main/java/ru/practicum/ewm/user/UserServiceImp.java
> +        return UserMapper.toUserDto(userRepository.save(inputUser));
У нас сохранение самое главное действие тут, давай не будеv прятать его, оно достойно отдельной строки кода!

Я бы предложил еще заимпортить статические методы и привести вот к такому виду

```
    public UserDto createByAdmin(NewUserRequestDto newUserRequestDto) {
        if (userRepository.existsByNameOrByEmail(newUserRequestDto.getName(), newUserRequestDto.getEmail())) {
            throw new AlreadyExistException("User with name=" + newUserRequestDto.getName()
                    + " or ematl=" + newUserRequestDto.getEmail() + " already exist");
        }

        User saved = userRepository.save(toUser(newUserRequestDto));

        return toUserDto(saved);
    }
```

2022-12-02 19:56 UTC, merged